algoritmo "Exercicio5"
// Função :
// Autor :
// Data : 5/9/2018
// Seção de Declarações 
var
   nome: caractere
   telefone: caractere
   endereco: caractere
   idade: inteiro
inicio
      escreva("Digite seu nome:")
      leia(nome)
      escreva ("Digite seu telefone:")
      leia(telefone)
      escreva("Digite seu endereço:")
      leia(endereco)
      escreva("Digite sua idade:")
      leia(idade)
fimalgoritmo
