algoritmo "Exercicio4"
// Função :
// Autor :
// Data : 5/9/2018
// Seção de Declarações 
var
   idade1: inteiro
   idade2: inteiro
   media: real
inicio
      escreval ("Digite a idade do zé:")
      leia(idade1)
      escreval ("Digite a idade do Pedrinho:")
      leia(idade2)
      escreval ("Media das idades do Zé e do Pedrinho:")
      media <- (idade1 + idade2) / 2 ;
      escreva(media)

fimalgoritmo
