algoritmo "Vetor"

var
   x: vetor [0..4] de inteiro
   i,j : inteiro
inicio
//Escreva um algoritmo que armazene em um vetor o quadrado dos números ímpares de 1 a 10. Imprima todos os valores armazenados..
       para i de 1 ate 10 passo 2 faca
            x[j] <- i*i
            Escreval ("O quadrado dos numeros impares sao:", x[j])
            j <- j+1
       fimpara
fimalgoritmo

