algoritmo "Vetor"

var
   x: vetor [0..4] de inteiro
   i : inteiro
inicio
// Escrever um algoritmo que possua um vetor inteiro de 5 posições com os dados fornecidos pelo usuário.
//Após preencher o vetor apresentar a posição e o valor preenchido na posição.
       para i de 0 ate 4 passo 1 faca
            Escreval ("Escreva um dado qqr:", "[", i, " ]")
            leia (x[i])
       fimpara
fimalgoritmo

