
Algoritmo "semnome"

Var
nome: caractere
idade: inteiro
n1, n2, n3, media: real
aprovado: logico
Inicio
Escreva("Informe o nome dx alunx: ")
Leia(nome)
Escreva("Informe a idade dx alunx: ")
Leia(idade)
Escreval("Informe as 3 notas dx alunx no bimestre: ")
Escreva("Nota 1: ")
Leia(n1)
Escreva("Nota 2: ")
Leia(n2)
Escreva("Nota 3: ")
Leia(n3)
media<- (n1+n2+n3)/3
Escreval("A média dx alunx é:", media,".")
aprovado <- verdadeiro
Escreva("Aprovado?:", aprovado)
Fimalgoritmo