algoritmo "Ecercicio03"
// Função :
// Autor :
// Data : 5/9/2018
// Seção de Declarações 
var
   nome: caractere
   idade: inteiro
   salario: real
   masculino: logico
inicio
      escreval("Digite seu nome:")
      leia(nome)
      escreval("Digite sua idade:")
      leia(idade)
      escreval ("Digite sua pretenção salarial:")
      leia(salario)
      escreval ("Digite seu sexo:")
      leia(masculino)
fimalgoritmo
