algoritmo "TiposDados"
// Função :
// Autor : Rodrigo Paulo
// Data : 5/9/2018
// Seção de Declarações 
var
   nome : caractere
   idade : inteiro
   salario : real
   masculino : logico
inicio
      nome <- "Maria"
      idade <- 18
      salario <- 100,00
      masculino <- falso
      escreval("Nome:",nome)
      escreval("Idade:", idade)
      escreval("Salario: ", salario)
      escreval("Masculino?: ", masculino)
fimalgoritmo
