algoritmo "Exercio04"

var
idade:inteiro
inicio
escreva("Digite a Idade: ")
leia (idade)

se (idade >=5) e (idade<=7) entao
escreva("infantil a")
senao
se (idade>=8) e (idade<=10) entao
escreva("infantil b")
senao
se (idade >=11) e (idade<=13) entao
escreva("juvenil a")
senao
se (idade>=14) e (idade<=17) entao
escreva("juvenil b")
senao
se (idade>18) entao
escreva("adultos")
senao
escreva("invalido")
fimse
fimse
fimse
fimse
fimse



fimalgoritmo
