algoritmo "Exercicio6recursividade"

var
   n: inteiro

funcao
   inicio

   fimfuncao

inicio
      Escreval ("Informe um valor para 'n':)
      Leia (n)
fimalgoritmo

//Crie um algoritmo para apresentar a tabuada, dado que que a função receberá qual o valor n que será feita a tabuada com base nesse valor:
//1 * N = 1N
//2 * N = 2N
//3 * N = 3N
//Utilize recursividade para trabalhar com esses valores.
