algoritmo "Exercicio02"
// Função : Escrever um algoritmo que leia dois valores inteiros distintos e informe qual é o maior.
// Autor : Rodrigo Paulo
// Data : 10/9/2018
// Seção de Declarações 
var
v1,v2:inteiro
inicio
escreval("Digite o primeiro valor: ")
leia(v1)
escreval("Digite o segundo valor: ")
leia(v2)
se v1 > v2 entao
escreval("Valor 1 é maior que valor 2")
senao
escreval("Valor 2 é maior que valor 1")
fimse
fimalgoritmo
