algoritmo "semnome"
// Função :
// Autor :
// Data : 05/09/2018
// Seção de Declarações 
var
idade: inteiro
nota: real
endereco: caractere
masculino: logico
inicio
escreva ("Digite a sua idade: ")
leia (idade)
escreva("Digite sua nota: ")
leia (nota)
escreva ("Digite seu endereço: ")
leia (endereco)
escreva ("Masculino? ")
leia (masculino)
Escreva("Idade: ", idade)
escreva("nota: ", nota)
escreva("endereço: ", endereco)
escreva("masculino?: ", masculino)
fimalgoritmo
