algoritmo "matriz"

var
   notas: vetor [1..10, 1..5] de inteiro
   linha, coluna, soma: inteiro
inicio
   PARA linha DE 1 ATE 10 FACA
      PARA coluna DE 1 ATE 5 FACA
         ESCREVA("armazene as notas: ",linha," ",coluna," ")
         LEIA (notas[linha,coluna])
      FIMPARA
   FIMPARA
  PARA linha DE 1 ATE 10 FACA
      PARA coluna DE 1 ATE 5 FACA
         ESCREVA("armazene as notas: ",linha," ",coluna," ")
         LEIA (notas[linha,coluna])
      FIMPARA
   FIMPARA
fimalgoritmo
