algoritmo "Exercicio3Funcao"

var
   num1, num2: inteiro
funcao numeromaior(): inteiro

   inicio
      Se num1 > num2 entao
         retorne num1
      Senao
         retorne num2
      Fimse
   fimfuncao
inicio
      Escreval ("Informe um numero '1':")
      Leia (num1)
      Escreval ("Informe um numero '2':")
      Leia (num2)
      Escreval ("O maior valor informado e:", numeromaior())
fimalgoritmo
