algoritmo "ExerciciosVisualG"
var
   nome: caractere
   telefone: caractere
   endereco: caractere
   idade: inteiro
inicio
      Escreval ("Questionario")
      Escreval ("Qual o seu nome?")
      Leia (nome)
      Escreval ("Qual o numero do seu telefone")
      Leia (telefone)
      Escreval ("Qual o seu endereco")
      Leia (endereco)
      Escreval ("Qual sua Idade?")
      Leia (idade)
fimalgoritmo
