algoritmo "exercicio1"
var

notaa: real
notab: real
notac: real
media: real
nome: caractere

inicio

escreval ("digite nota a: ")
leia (notaa)
escreval ("digite nota b: ")
leia (notab)
escreval ("digite nota c: ")
leia (notac)
media <- notaa+notab+notac/3
escreval ("digite nome: ")
leia (nome)
se media <7 entao
escreval ("reprovado")
senao
escreval ("aprovado")
fimse




fimalgoritmo
