algoritmo "maior numero"
var
primeiro, segundo: inteiro
inicio
escreval("digite primerio numero")
leia(primeiro)
escreval("digite segundo número")
leia(segundo)
se primeiro > segundo entao
    Escreval("O valor: ", primeiro, " é maior que: ", segundo)
   senao
      Escreval("O valor: ", segundo, " é maior que: ", primeiro)
   fimse
fimalgoritmo
   
fimse
se numero1 < menor entao
   menor >= numero1
fimse



fimalgoritmo
