algoritmo "TiposDados"
var
nome, endereco, telefone: caractere
idade: inteiro
inicio
Escreva("Como você se chama? ")
Leia(nome)
Escreva("Qual a sua idade? ")
Leia(idade)
Escreva("Onde você mora? ")
Leia(endereco)
Escreva("Qual o seu número de telefone? ")
Leia(telefone)
Escreval("")
Escreval("Ok, entendido!")
Escreval("Você se chama ", nome, ", tem ", idade, " anos e reside em ", endereco, ".")
Escreval("E o seu telefone para contato é ", telefone, ".")
Escreval("Muito prazer!")
fimalgoritmo
