algoritmo "avulso"
// Função : escreval (count)
// Autor :
// Data : 19/9/2018
// Seção de Declarações
var
n1,n2,total:inteiro

inicio

      repita
            escreval ("digite o numero 1: ")
            leia (n1)
            escreval ("digite o numero 2: ")
            leia (n2)
             total <- n1 + n2
             escreval (" soma de n1 + n2 é: ", total)
             ate total > 15

fimalgoritmo
