algoritmo "extra2"

var

  a: vetor [1..5] de inteiro
  b: vetor [1..5] de inteiro
  c: vetor [1..5] de inteiro
  i:inteiro
inicio
i <-0
para i de 1 ate 5 faca
     escreval ( "valor da posição: ",i,": ")
     leia (a[i])
para i de 1 ate 5 faca
     escreval ( "valor da posição: ",i,": ")
     leia (b[i])
   c<-([a])*(b[i])
fimpara
fimpara
     escreval ("o valor de c é: ", c)

fimalgoritmo
