algoritmo "semnome"
var
b, c, Ra, Rb, Rc, Rd: real
Re, Rf, Rg, Rh: inteiro
inicio
b <- 1
c <- 2
Ra <- (20 - 15) / (2 * b)
Rb <- 20 - 15 / (2 * c)
Rc <- 2 * 5 / 20 + 30 / 15 * 2
Rd <- 2 *(5 / 20) + 30 /(15 * 2)
Re <- 23 div 4
Rf <- 23 mod 4
Rg <- 35 div 6 + 2
Rh <- 35 div 6 - 2
Escreval (Ra)
Escreval (Rb)
Escreval (Rc)
Escreval (Rd)
Escreval (Re)
Escreval (Rf)
Escreval (Rg)
Escreval (Rh)

fimalgoritmo
